# Synthea Configuration Properties
exporter.fhir.export = true
exporter.fhir.transaction_bundle = true
exporter.hospital.fhir.export = false
exporter.practitioner.fhir.export = false
generate.append_numbers_to_person_names = false
